#!/bin/bash
# Generates the default iwasm-wrapper script required by binfmt_register.sh

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/../wali_config.sh

# Save default environment variables in ".walienv" in root WALI dir
env &> $WALI_ROOT_DIR/.walienv

# Write wrapper script ("iwasm-wrapper") with default settings
# Modify default settings as needed
cat <<EOT > $SCRIPT_DIR/iwasm-wrapper
#!/bin/bash
### Generated by "binfmt_register.sh" in WALI
### Wrapper for running WASM programs by pointing to built iwasm in root WALI dir 

VERBOSITY=\${WALI_VERBOSE:-0}
exec $WALI_ROOT_DIR/iwasm -v=\$VERBOSITY --stack-size=524288 --max-threads=100 --env-file=$WALI_ROOT_DIR/.walienv "\$@"
EOT
if [ $? -ne 0 ]; then
  echo "Error writing iwasm-wrapper"
  exit 1
fi
echo "Successfully generated iwasm-wrapper"

# Generate the iwali
cat <<EOT > $SCRIPT_DIR/iwali.conf
### Generated by "binfmt_register.sh" in WALI
### Binfmt.d configuration settings for iwasm interpreter 
:wali-interp:M::\x00asm::$SCRIPT_DIR/iwasm-wrapper:
:wali-aot:M::\x00aot::$SCRIPT_DIR/iwasm-wrapper:
EOT
if [ $? -ne 0 ]; then
  echo "Error writing iwali-conf"
  exit 1
fi
echo "Successfully generated iwali-conf"

